# Generated by Django 4.1.7 on 2023-03-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="General_Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("account", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="assetclass",
            options={
                "verbose_name": "Asset Class",
                "verbose_name_plural": "Asset Classes",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="allocated_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("ZWL", "ZWL"),
                    ("ZAR", "ZAR"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="person_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
