# Generated by Django 4.1.7 on 2023-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_general_ledger_alter_assetclass_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="general_ledger_account",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL8373", "AL8373"),
                    ("AL8374", "AL8374"),
                    ("AL8375", "AL8375"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
