# Generated by Django 4.1.7 on 2023-03-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_asset_general_ledger_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="general_ledger_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.general_ledger",
            ),
        ),
    ]
