# Generated by Django 4.1.7 on 2023-03-11 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_asset_general_ledger_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="received_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
