# Generated by Django 4.1.7 on 2023-03-11 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_asset_received_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="allocated_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
