# Generated by Django 4.1.7 on 2023-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_asset_allocated_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="purchase_request_document",
            field=models.FileField(
                blank=True, null=True, upload_to="hardware requests"
            ),
        ),
    ]
