# Generated by Django 4.1.7 on 2023-03-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_asset_purchase_request_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "managed": True,
                "ordering": ("-date_created", "-tag"),
                "permissions": (("can_create_asset", "Can Create Asset"),),
            },
        ),
        migrations.AlterField(
            model_name="hardwarerequisition",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.asset",
            ),
        ),
    ]
