# Generated by Django 4.0.8 on 2022-11-22 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_clear', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_asset_tag', models.CharField(blank=True, max_length=255)),
                ('new_active_directory_name', models.CharField(blank=True, max_length=255)),
                ('old_active_directory_name', models.CharField(blank=True, max_length=255)),
                ('custodian', models.TextField(blank=True, max_length=255, null=True)),
                ('date_configured', models.DateTimeField(auto_now_add=True)),
                ('cleared', models.BooleanField(blank=True, default=False)),
                ('date_cleared', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clearings', to=settings.AUTH_USER_MODEL)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL)),
                ('software_installed', models.ManyToManyField(blank=True, null=True, to='application.software')),
            ],
        ),
    ]
