# Generated by Django 4.1.7 on 2023-03-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='software_installed',
        ),
    ]
